// =============================================================
// SINGLE SOURCE OF TRUTH FOR ALL PORTFOLIO CONTENT
// Edit the values below to fill in your real details, projects,
// skills, featured deep dive, and reflection. The UI updates
// automatically. Placeholders are marked with TODO.
// =============================================================

export const profile = {
  name: "Somtochukwu Emmanuel Umeh", // TODO: your full name
  title: "Full Stack and DevOps Engineer", // TODO: your role / title
  bio: "Full stack and DevOps engineer focused on reliable APIs, production deployments, and systems you can defend under load. During HNG I shipped backend services, AI-integrated APIs, and a live security monitoring stack on real infrastructure.",
  location: "Northampton, United Kingdom (GMT+1)", // TODO: location or timezone
  email: "emmanueldennise99@gmail.com",
  github: "https://github.com/Nuel-09",
  linkedin: "https://www.linkedin.com/in/somtochukwu-umeh-3727271aa/",
  twitter: "", // optional, leave "" to hide
  resume: "", // optional link to resume/CV, leave "" to hide
};

// One entry per significant project. A project can expose multiple repos via
// the `links` array (e.g. backend + CLI + web portal). Simpler projects can use
// the single `repo`/`demo` fields instead. Leave a field "" / [] to hide it.
export const projects = [
  {
    name: "Insighta Labs — Queryable Intelligence Engine",
    description:
      "A profile-intelligence platform built around a queryable API. It enriches person-profile data (gender, age, nationality) from external providers and exposes advanced filtering, sorting, pagination, and rule-based natural-language search. Shipped with a global CLI and a React web portal as first-class clients.",
    stack: [
      "Node.js",
      "Express",
      "MongoDB",
      "Mongoose",
      "JWT",
      "GitHub OAuth (PKCE)",
      "React",
      "Vite",
    ],
    contribution:
      "Built the full system end to end: the Express/MongoDB API (GitHub OAuth with PKCE, JWT access/refresh with rotation, RBAC, rule-based NL search, streaming CSV ingestion, in-memory query cache with deterministic query normalization, rate limiting, request logging, CI), the global Node.js CLI client, and the React + Vite web portal (HTTP-only cookies, CSRF).",
    links: [
      { label: "Backend API", url: "https://github.com/Nuel-09/HNG_STAGE-1" },
      { label: "CLI", url: "https://github.com/Nuel-09/Insighta-Cli" },
      { label: "Web Portal", url: "https://github.com/Nuel-09/Insighta-WebPortal" },
    ],
    image: "", // screenshot path/URL (leave "" to hide)
  },
  {
    name: "Flowbrand Marketing Service (SEIL)",
    description:
      "NestJS HTTP API for SEIL, a guided marketing-strategy product for small businesses. Users authenticate with JWT, upload PDF or DOCX business documents, and receive a structured marketing funnel (awareness → engagement → conversion → retention) generated by Anthropic Claude from extracted document text. This service is my full backend implementation within the broader SEIL / Flowbrand product at https://flowbrand.hng14.com/.",
    stack: [
      "NestJS",
      "TypeORM",
      "PostgreSQL",
      "JWT",
      "Anthropic Claude",
      "Swagger",
      "Docker",
    ],
    contribution:
      "Owned and delivered the marketing service end to end: JWT auth, multipart uploads with PDF/DOCX validation and text extraction (pdf-parse, mammoth), upload progress tracking, Claude-powered funnel generation with strict JSON schema validation, TypeORM persistence, Swagger at /api/v1/docs, Docker Compose for local Postgres + API, and production deploy on Render.",
    repo: "https://github.com/Nuel-09/Flowbrand-marketing-service",
    demo: "https://flowbrand-marketing-service.onrender.com/api/v1/docs",
    image: "",
  },
  {
    name: "Anomaly Detection Engine (DevSecOps)",
    description:
      "Real-time HTTP anomaly detection for a Nextcloud stack behind Nginx on a VPS. A Python daemon tails JSON access logs, applies 60-second sliding-window rates and a rolling statistical baseline (z-score and spike rules), bans abusive IPs via host iptables, notifies Slack, keeps an audit trail, and exposes a live Flask metrics dashboard.",
    stack: [
      "Python",
      "Docker Compose",
      "Nginx",
      "iptables",
      "Flask",
      "DigitalOcean",
    ],
    contribution:
      "Designed and deployed the full stack on Ubuntu: Docker Compose for Nextcloud, Nginx, and the detector (host network + NET_ADMIN for DOCKER-USER iptables bans), UFW and cloud firewall rules, DuckDNS for the public dashboard, deque-based sliding windows and 30-minute rolling baselines with hourly slots, auto-unban backoff, and documented VPS setup end to end in the repo README.",
    repo: "https://github.com/Nuel-09/DevSecOps-Project",
    demo: "",
    image: "",
  },
];

// Each skill should point back to a project (per the rubric).
// Remove any skill you can't back with a project.
const INSIGHTA = "Insighta Labs — Queryable Intelligence Engine";
const FLOWBRAND = "Flowbrand Marketing Service (SEIL)";
const DEVSECOPS = "Anomaly Detection Engine (DevSecOps)";

export const skills = [
  { name: "API Design", project: FLOWBRAND },
  { name: "Authentication (JWT)", project: FLOWBRAND },
  { name: "Databases (PostgreSQL)", project: FLOWBRAND },
  { name: "Databases (MongoDB)", project: INSIGHTA },
  { name: "Caching", project: INSIGHTA },
  { name: "Data Ingestion (PDF/DOCX + AI)", project: FLOWBRAND },
  { name: "Data Ingestion (streaming CSV)", project: INSIGHTA },
  { name: "Testing (CI)", project: FLOWBRAND },
  { name: "Deployment (Render + Docker)", project: FLOWBRAND },
  { name: "Documentation (Swagger)", project: FLOWBRAND },
  { name: "DevOps (Docker Compose + VPS)", project: DEVSECOPS },
  { name: "Security (anomaly detection + iptables)", project: DEVSECOPS },
  { name: "Logging & monitoring", project: DEVSECOPS },
];

// Featured deep dive — Flowbrand Marketing Service (SEIL).
export const featured = {
  projectName: "Flowbrand Marketing Service (SEIL)",
  summary:
    "NestJS API that turns uploaded business documents into a four-stage marketing funnel using Claude, with JWT auth and Swagger-documented endpoints under /api/v1.",
  problem:
    "SEIL targets small business owners who need a clear marketing plan but lack marketing expertise. The product must accept real business documents (PDF/DOCX), extract usable text, and return a consistent funnel structure (awareness, engagement, conversion, retention) that non-technical users can follow—without inventing unsupported claims from thin documents.",
  architecture:
    "Clients call the API at global prefix /api/v1. A global ValidationPipe whitelists DTO fields. JWT guards protect funnel routes. Upload flow: Multer receives the file in memory (≤ 5 MiB), FunnelsUploadService validates MIME/extension, persists metadata and file under UPLOAD_STORAGE_ROOT, runs pdf-parse or mammoth extraction, and transitions status (uploading → processing → ready). Clients poll GET /funnels/upload/progress/:uploadId. Generation: POST /funnels/generate-from-upload with uploadId checks ownership and ready status, FunnelAiService calls Anthropic Messages API with a fixed system prompt and capped document text, coerceJsonFromModelText strips markdown fences, parseMarketingFunnelResult enforces the four string fields, and the result is stored in funnel_generations. Auth uses bcrypt + @nestjs/jwt. Interactive docs live at /api/v1/docs.",
  endpoints: [
    { method: "POST", path: "/api/v1/auth/register", purpose: "Create account and return JWT." },
    { method: "POST", path: "/api/v1/auth/login", purpose: "Issue JWT access token." },
    { method: "POST", path: "/api/v1/funnels/upload", purpose: "Multipart PDF/DOCX upload; extract text and return uploadId + status." },
    { method: "GET", path: "/api/v1/funnels/upload/progress/:uploadId", purpose: "Poll upload status for the authenticated owner." },
    { method: "POST", path: "/api/v1/funnels/generate-from-upload", purpose: "Generate awareness/engagement/conversion/retention funnel from a ready upload via Claude." },
    { method: "GET", path: "/api/v1/health", purpose: "Liveness check (no DB dependency)." },
  ],
  challenge:
    "Claude sometimes returned JSON wrapped in markdown code fences or omitted required funnel fields, which broke parsing and left the API returning opaque 502 errors to clients.",
  solution:
    "Added coerceJsonFromModelText to strip ```json fences when the model ignores instructions, and parseMarketingFunnelResult to validate exactly four non-empty string keys (awareness, engagement, conversion, retention) with clear errors. Unit tests cover parsing edge cases in funnel-ai.service.spec.ts. Upload paths return structured SeilException codes (e.g. UPLOAD_NOT_READY, AI_NOT_CONFIGURED) so clients and Swagger consumers get actionable messages instead of generic failures.",
};

// Honest, specific, concise.
export const reflection = [
  "During HNG I moved from shipping isolated endpoints to owning full systems: Insighta Labs taught me to design APIs clients can trust (auth, RBAC, caching, ingestion at scale), Flowbrand SEIL pushed me to integrate AI safely behind strict schemas and clear error codes, and the DevSecOps anomaly engine forced me to think about production—firewalls, host networking, and automated response when traffic misbehaves.",
  "I improved by documenting as I built (Swagger, README runbooks, architecture notes) and by testing failure paths early—invalid uploads, missing API keys, malformed model JSON, ban/unban cycles—instead of only the happy path. I now default to explicit validation, structured errors, and deployment steps a reviewer can reproduce without guessing env vars or ports.",
  "The biggest shift is confidence under deadline: I can scope a backend or DevOps deliverable, break it into deployable pieces, and leave proof (repos, live URLs, metrics) that shows what I built and how it behaves in the real world.",
];
