// =============================================================
// SINGLE SOURCE OF TRUTH FOR ALL PORTFOLIO CONTENT
// Edit the values below to fill in your real details, projects,
// skills, featured deep dive, and reflection. The UI updates
// automatically. Placeholders are marked with TODO.
// =============================================================

export const profile = {
  name: "Somtochukwu Emmanuel Umeh", // TODO: your full name
  title: "Full Stack and DevOps Engineer", // TODO: your role / title
  bio: "Full stack and DevOps engineer focused on reliable APIs, production deployments, and systems you can defend under load. During HNG I shipped backend services, AI-integrated APIs, and a live security monitoring stack on real infrastructure.",
  location: "Northampton, United Kingdom (GMT+1)", // TODO: location or timezone
  email: "emmanueldennise99@gmail.com",
  github: "https://github.com/Nuel-09",
  linkedin: "https://www.linkedin.com/in/somtochukwu-umeh-3727271aa/",
  twitter: "", // optional, leave "" to hide
  resume: "", // optional link to resume/CV, leave "" to hide
};

// One entry per significant project. A project can expose multiple repos via
// the `links` array (e.g. backend + CLI + web portal). Simpler projects can use
// the single `repo`/`demo` fields instead. Leave a field "" / [] to hide it.
export const projects = [
  {
    name: "Dilamme Job Scheduler (Stage 9)",
    description:
      "Full-stack background job scheduler for Dilamme (HNG Stage 9): REST API to create standalone, scheduled, recurring, and DAG workflow jobs; independent scheduler and worker processes; PostgreSQL as source of truth; Redis for distributed locks and SSE pub/sub; React dashboard with live updates.",
    stack: [
      "Node.js",
      "TypeScript",
      "Fastify",
      "PostgreSQL",
      "Redis",
      "Drizzle ORM",
      "React",
      "pnpm",
    ],
    contribution:
      "Built and deployed the monorepo end to end: Fastify API with Swagger and SSE event stream, scheduler daemon (indexed min-heap mirror, priority aging, due-job promotion), worker daemon (timing wheel for retries/recurring, handler registry, FOR UPDATE SKIP LOCKED claims + Redis locks), DLQ with manual retry and threshold alerts, transactional job_logs audit trail, React dashboard, VPS deploy with Nginx and DuckDNS.",
    repo: "https://github.com/Nuel-09/dilamme-Job-Scheduler",
    demo: "https://dilamme-jobscheduler.duckdns.org/",
    image: "",
  },
  {
    name: "Insighta Labs — Queryable Intelligence Engine",
    description:
      "A profile-intelligence platform built around a queryable API. It enriches person-profile data (gender, age, nationality) from external providers and exposes advanced filtering, sorting, pagination, and rule-based natural-language search. Shipped with a global CLI and a React web portal as first-class clients.",
    stack: [
      "Node.js",
      "Express",
      "MongoDB",
      "Mongoose",
      "JWT",
      "GitHub OAuth (PKCE)",
      "React",
      "Vite",
    ],
    contribution:
      "Built the full system end to end: the Express/MongoDB API (GitHub OAuth with PKCE, JWT access/refresh with rotation, RBAC, rule-based NL search, streaming CSV ingestion, in-memory query cache with deterministic query normalization, rate limiting, request logging, CI), the global Node.js CLI client, and the React + Vite web portal (HTTP-only cookies, CSRF).",
    links: [
      { label: "Backend API", url: "https://github.com/Nuel-09/HNG_STAGE-1" },
      { label: "CLI", url: "https://github.com/Nuel-09/Insighta-Cli" },
      { label: "Web Portal", url: "https://github.com/Nuel-09/Insighta-WebPortal" },
    ],
    image: "", // screenshot path/URL (leave "" to hide)
  },
  {
    name: "Flowbrand Marketing Service (SEIL)",
    description:
      "NestJS HTTP API for SEIL, a guided marketing-strategy product for small businesses. Users authenticate with JWT, upload PDF or DOCX business documents, and receive a structured marketing funnel (awareness → engagement → conversion → retention) generated by Anthropic Claude from extracted document text. This service is my full backend implementation within the broader SEIL / Flowbrand product at https://flowbrand.hng14.com/.",
    stack: [
      "NestJS",
      "TypeORM",
      "PostgreSQL",
      "JWT",
      "Anthropic Claude",
      "Swagger",
      "Docker",
    ],
    contribution:
      "Owned and delivered the marketing service end to end: JWT auth, multipart uploads with PDF/DOCX validation and text extraction (pdf-parse, mammoth), upload progress tracking, Claude-powered funnel generation with strict JSON schema validation, TypeORM persistence, Swagger at /api/v1/docs, Docker Compose for local Postgres + API, and production deploy on Render.",
    repo: "https://github.com/Nuel-09/Flowbrand-marketing-service",
    demo: "https://flowbrand-marketing-service.onrender.com/api/v1/docs",
    image: "",
  },
  {
    name: "Anomaly Detection Engine (DevSecOps)",
    description:
      "Real-time HTTP anomaly detection for a Nextcloud stack behind Nginx on a VPS. A Python daemon tails JSON access logs, applies 60-second sliding-window rates and a rolling statistical baseline (z-score and spike rules), bans abusive IPs via host iptables, notifies Slack, keeps an audit trail, and exposes a live Flask metrics dashboard.",
    stack: [
      "Python",
      "Docker Compose",
      "Nginx",
      "iptables",
      "Flask",
      "DigitalOcean",
    ],
    contribution:
      "Designed and deployed the full stack on Ubuntu: Docker Compose for Nextcloud, Nginx, and the detector (host network + NET_ADMIN for DOCKER-USER iptables bans), UFW and cloud firewall rules, DuckDNS for the public dashboard, deque-based sliding windows and 30-minute rolling baselines with hourly slots, auto-unban backoff, and documented VPS setup end to end in the repo README.",
    repo: "https://github.com/Nuel-09/DevSecOps-Project",
    demo: "http://mydetector.duckdns.org",
    image: "",
  },
];

// Each skill should point back to a project (per the rubric).
// Remove any skill you can't back with a project.
const INSIGHTA = "Insighta Labs — Queryable Intelligence Engine";
const FLOWBRAND = "Flowbrand Marketing Service (SEIL)";
const DEVSECOPS = "Anomaly Detection Engine (DevSecOps)";
const DILAMME = "Dilamme Job Scheduler (Stage 9)";

export const skills = [
  { name: "API Design", project: DILAMME },
  { name: "Authentication (JWT)", project: FLOWBRAND },
  { name: "Databases (PostgreSQL)", project: DILAMME },
  { name: "Databases (MongoDB)", project: INSIGHTA },
  { name: "Background Jobs", project: DILAMME },
  { name: "Queues (heap + timing wheel)", project: DILAMME },
  { name: "Caching", project: INSIGHTA },
  { name: "Data Ingestion (PDF/DOCX + AI)", project: FLOWBRAND },
  { name: "Data Ingestion (streaming CSV)", project: INSIGHTA },
  { name: "Testing (CI + integration)", project: DILAMME },
  { name: "Deployment (VPS + Nginx + DuckDNS)", project: DILAMME },
  { name: "Documentation (Swagger + architecture)", project: DILAMME },
  { name: "DevOps (Docker Compose + VPS)", project: DEVSECOPS },
  { name: "Security (anomaly detection + iptables)", project: DEVSECOPS },
  { name: "Logging & monitoring", project: DILAMME },
];

// Featured deep dive — Dilamme Job Scheduler (Stage 9).
export const featured = {
  projectName: "Dilamme Job Scheduler (Stage 9)",
  summary:
    "Distributed background job system with heap-based priority scheduling, DAG workflows, DLQ, hybrid timing-wheel retries, and a live React dashboard over SSE.",
  problem:
    "Dilamme needed reliable background processing: priority ordering without starvation, scheduled and recurring jobs, multi-step workflows with dependencies, safe retries, a dead-letter path for exhausted failures, and operators who could see job state change in real time—not poll a REST API every few seconds.",
  architecture:
    "pnpm monorepo with four processes: Fastify API (REST + Swagger + SSE at /api/events), scheduler daemon (~500ms tick: priority aging, promote due pending jobs via indexed min-heap mirror, sweep overdue retries), and worker daemon(s) (claim with PostgreSQL FOR UPDATE SKIP LOCKED, Redis NX lock per job, run handlers, timing wheel for 1s/5s/25s backoff with jitter). PostgreSQL (Drizzle) is the source of truth for jobs, dependencies, and transactional job_logs; Redis is only locks and pub/sub. Flow: POST /api/jobs creates pending rows → scheduler promotes eligible jobs (DAG deps satisfied, scheduled_at <= now) → worker claims and executes → success completes or failure schedules retry/DLQ → Redis publishes to SSE for the React dashboard. Scheduler rebuilds heap from DB every ~60s; scheduler sweep releases awaiting_retry rows if a worker timing wheel is lost.",
  endpoints: [
    { method: "POST", path: "/api/jobs", purpose: "Create standalone, scheduled, recurring, or DAG workflow jobs." },
    { method: "GET", path: "/api/jobs", purpose: "List and filter jobs for the dashboard and API clients." },
    { method: "GET", path: "/api/jobs/:id", purpose: "Fetch job detail, status, and execution metadata." },
    { method: "POST", path: "/api/jobs/:id/cancel", purpose: "Cancel pending jobs immediately or flag in-flight jobs for safe abort." },
    { method: "GET", path: "/api/dlq", purpose: "List dead-letter jobs after retries are exhausted." },
    { method: "POST", path: "/api/dlq/:id/retry", purpose: "Manually requeue a failed job from the DLQ." },
    { method: "GET", path: "/api/events", purpose: "SSE stream; Redis pub/sub pushes live job transitions to the UI." },
    { method: "GET", path: "/health", purpose: "Liveness check for deploy and Nginx routing." },
  ],
  challenge:
    "Running multiple worker processes risked duplicate execution, and in-memory timing wheels are lost on worker restart—so retries and recurring schedules could stall unless the database and scheduler could recover them without double-firing jobs.",
  solution:
    "Workers claim with FOR UPDATE SKIP LOCKED so only one row owner wins per job, then acquire a Redis job:{id}:lock (NX EX 300) before running handlers. Failed runs set awaiting_retry=true and scheduled_at in PostgreSQL while the timing wheel handles the fast path; the scheduler sweep idempotently clears awaiting_retry when scheduled_at <= now, and workers rebuild their wheels from DB on startup. Every status change writes job_logs in the same transaction as the job update, and SSE events keep the dashboard consistent without polling.",
};

// Honest, specific, concise.
export const reflection = [
  "During HNG I moved from shipping isolated endpoints to owning full systems: Insighta Labs taught me multi-client auth and API hardening, Flowbrand SEIL pushed me to integrate AI behind strict schemas, the DevSecOps engine forced production thinking (firewalls, iptables, live metrics), and Dilamme Stage 9 tied it together (background jobs, queues, durability, and a dashboard that stays live over SSE).",
  "I improved by documenting as I built (Swagger, architecture docs, deployment runbooks) and by designing for failure early, duplicate worker claims, lost timing wheels, malformed LLM JSON, ban/unban cycles, etc. instead of only the happy path. I now default to PostgreSQL as source of truth, explicit state machines, structured errors, and deploy steps a reviewer can reproduce.",
  "The biggest shift is confidence under deadline: I can scope a backend or DevOps deliverable, split it into API/scheduler/worker boundaries when needed, and leave proof (repos, live URLs, Swagger) that shows what I built and how it behaves on real infrastructure.",
];
